---
data:
  filepath: data/sharedata.csv
  headers:
    - assetType
    - price
    - ticker
    - quantity
    - eventType
    - date
    - currency
    - commision
  events: 
    - buy
    - sell
    - split
api:
  apiKeysFile: backends/apis/API_keys.yaml
  apiBackend: financialModellingPrep
dataConversions:
  dateFormat: '%d/%m/%Y'
  defaultCurrency: AUD
display:
  colWidth: 12

