---
data:
  filepath: data/sharedata.csv
  headers:
    - assetType
    - price
    - ticker
    - quantity
    - eventType
    - date
    - currency
    - commision
  events: 
    - buy
    - sell
    - split
api:
  apiKeysFile: API_backends/API_keys.yaml
  apiBackend: twelveData
dataConversions:
  dateFormat: '%d/%m/%Y'
  defaultCurrency: USD
display:
  colWidth: 12

