---
dataPath: sharedata.csv
api:
  apiKeysFile: API_backends/API_keys.yaml
  apiBackend: twelveData
delims: 
  assetType: Asset_Type
  price: Share_Price
  ticker: Ticker
  quantity: Quantity
  eventType: Type
  date: Date
  currency: Currency
  buy: BUY
  sell: SELL
  split: SPLIT
dataConversions:
  dateFormat: '%d/%m/%Y'
defaultCurrency: AUD

